[theme]
base = "dark"
primaryColor = "#ff4b4b"
backgroundColor = "#0b0d13"
secondaryBackgroundColor = "#161922"
textColor = "#f3f4f6"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
